import dotenv from "dotenv";
import mongoose from "mongoose";
import { connectDB } from "./db/dbconnection.js";
import DayBook from "./models/dayBook.js";
import Partner from "./models/partner.js";
import PartnerTransaction from "./models/partnerTransaction.js";

dotenv.config();

/* ═══════════════════════════════════════════════════════════════════════
   Seed: Metro Hospital, Haridwar
   Source: metro.xlsx (real historical bookkeeping data)
   Date range: 2026-01-01 to 2026-05-31  (155 days)

   Mapping notes (see chat for full rationale):
   - openingCash / totalSale / totalCash / cashExpenses / cashInHand are
     copied DIRECTLY from the spreadsheet's own daily totals (ground truth),
     not re-derived from the granular columns below.
   - kitchenSale / coffeeShop / officialCr / personalCr are a best-effort
     breakdown from the sheet's sale + credit columns, for display purposes.
   - "Cash Received From <partner>" columns became PartnerTransaction
     (type "receive"); trailing per-partner advance columns became
     PartnerTransaction (type "transfer"). Non-partner columns (e.g.
     "Others"/"Hospital"/"Pantry") were left out of partner transactions.
   - Vendor "Credit Purchase" columns are not represented (no schema field).
═══════════════════════════════════════════════════════════════════════ */

const SHOP_ID = "6a82d8551a779efb7177420c";
const RANGE_START = new Date("2026-01-01T00:00:00.000Z");
const RANGE_END = new Date("2026-06-01T00:00:00.000Z");

const rawEntries = [
  {
    date: "2026-01-01",
    openingCash: 6512,
    kitchenSale: 550,
    coffeeShop: 2592,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 9200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 9200,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 3520,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 672,
      "Sweet/Ice Cream": 104,
      "Travel Expense": 6356,
    },
    cashExpenses: 15896,
    totalSale: 3142,
    totalCash: 19654,
    cashInHand: 3758,
  },
  {
    date: "2026-01-02",
    openingCash: 3758,
    kitchenSale: 560,
    coffeeShop: 3454,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2622,
    },
    cashExpenses: 3037,
    totalSale: 4014,
    totalCash: 7772,
    cashInHand: 4735,
  },
  {
    date: "2026-01-03",
    openingCash: 4735,
    kitchenSale: 580,
    coffeeShop: 2939,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 116600,
    advanceEntries: [
      {
        name: "Staff",
        amount: 116600,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 672,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 2779,
    },
    cashExpenses: 119784,
    totalSale: 3519,
    totalCash: 124854,
    cashInHand: 5070,
  },
  {
    date: "2026-01-04",
    openingCash: 5070,
    kitchenSale: 100,
    coffeeShop: 2324,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 3450,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 704,
      "Travel Expense": 4514,
    },
    cashExpenses: 4559,
    totalSale: 2424,
    totalCash: 7494,
    cashInHand: 2935,
  },
  {
    date: "2026-01-05",
    openingCash: 2935,
    kitchenSale: 600,
    coffeeShop: 2842,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      Egg: 230,
      "Milk/Curd/Paneer": 672,
      "Room Rent 2": 6000,
      Crockery: 100,
      "Travel Expense": 8932,
    },
    cashExpenses: 9267,
    totalSale: 3442,
    totalCash: 6377,
    cashInHand: -2890,
  },
  {
    date: "2026-01-06",
    openingCash: -2890,
    kitchenSale: 560,
    coffeeShop: 3557,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 612,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 1009,
    },
    cashExpenses: 1439,
    totalSale: 4117,
    totalCash: 1227,
    cashInHand: -212,
  },
  {
    date: "2026-01-07",
    openingCash: -212,
    kitchenSale: 700,
    coffeeShop: 3983,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Bread/Butter": 420,
      "Milk/Curd/Paneer": 704,
      "Misc/Repair": 60,
      "Travel Expense": 2964,
    },
    cashExpenses: 3549,
    totalSale: 4683,
    totalCash: 4471,
    cashInHand: 922,
  },
  {
    date: "2026-01-08",
    openingCash: 922,
    kitchenSale: 560,
    coffeeShop: 3413,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 200,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2622,
    },
    cashExpenses: 3347,
    totalSale: 3973,
    totalCash: 4895,
    cashInHand: 1548,
  },
  {
    date: "2026-01-09",
    openingCash: 1548,
    kitchenSale: 600,
    coffeeShop: 3034,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 3875,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 5077,
    },
    cashExpenses: 5580,
    totalSale: 3634,
    totalCash: 5182,
    cashInHand: -398,
  },
  {
    date: "2026-01-10",
    openingCash: -398,
    kitchenSale: 500,
    coffeeShop: 4205,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 762,
      "Travel Expense": 2542,
    },
    cashExpenses: 3107,
    totalSale: 4705,
    totalCash: 4307,
    cashInHand: 1200,
  },
  {
    date: "2026-01-11",
    openingCash: 1200,
    kitchenSale: 120,
    coffeeShop: 1699,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 80,
      "Bread/Butter": 360,
      Egg: 230,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 1282,
    },
    cashExpenses: 1377,
    totalSale: 1819,
    totalCash: 3019,
    cashInHand: 1642,
  },
  {
    date: "2026-01-12",
    openingCash: 1642,
    kitchenSale: 700,
    coffeeShop: 3146,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 612,
      Conveyance: 200,
      "Travel Expense": 2802,
    },
    cashExpenses: 2842,
    totalSale: 3846,
    totalCash: 5488,
    cashInHand: 2646,
  },
  {
    date: "2026-01-13",
    openingCash: 2646,
    kitchenSale: 600,
    coffeeShop: 3052,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 2155,
      "Milk/Curd/Paneer": 812,
      "Travel Expense": 4667,
    },
    cashExpenses: 4887,
    totalSale: 3652,
    totalCash: 6298,
    cashInHand: 1411,
  },
  {
    date: "2026-01-14",
    openingCash: 1411,
    kitchenSale: 400,
    coffeeShop: 2941,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 70,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 687,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 3164,
    },
    cashExpenses: 3399,
    totalSale: 3341,
    totalCash: 4752,
    cashInHand: 1353,
  },
  {
    date: "2026-01-15",
    openingCash: 1353,
    kitchenSale: 600,
    coffeeShop: 2527,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 70,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2382,
    },
    cashExpenses: 2567,
    totalSale: 3127,
    totalCash: 4480,
    cashInHand: 1913,
  },
  {
    date: "2026-01-16",
    openingCash: 1913,
    kitchenSale: 600,
    coffeeShop: 3020,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 200,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 3730,
      "Milk/Curd/Paneer": 687,
      "Travel Expense": 4647,
    },
    cashExpenses: 5322,
    totalSale: 3620,
    totalCash: 5533,
    cashInHand: 211,
  },
  {
    date: "2026-01-17",
    openingCash: 211,
    kitchenSale: 560,
    coffeeShop: 3046,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 797,
      "Travel Expense": 3167,
    },
    cashExpenses: 3342,
    totalSale: 3606,
    totalCash: 3817,
    cashInHand: 475,
  },
  {
    date: "2026-01-18",
    openingCash: 475,
    kitchenSale: 100,
    coffeeShop: 1998,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 60,
      "Bread/Butter": 58,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2430,
    },
    cashExpenses: 2730,
    totalSale: 2098,
    totalCash: 2573,
    cashInHand: -157,
  },
  {
    date: "2026-01-19",
    openingCash: -157,
    kitchenSale: 650,
    coffeeShop: 4282,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 130,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 612,
      "Misc/Repair": 1300,
      Conveyance: 300,
      "Travel Expense": 2932,
    },
    cashExpenses: 3488,
    totalSale: 4932,
    totalCash: 4775,
    cashInHand: 1287,
  },
  {
    date: "2026-01-20",
    openingCash: 1287,
    kitchenSale: 660,
    coffeeShop: 4058,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 612,
      Conveyance: 80,
      "Travel Expense": 2837,
    },
    cashExpenses: 3385,
    totalSale: 4718,
    totalCash: 6005,
    cashInHand: 2620,
  },
  {
    date: "2026-01-21",
    openingCash: 2620,
    kitchenSale: 600,
    coffeeShop: 3526,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "Veg/Fruit": 1355,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 687,
      "Travel Expense": 2747,
    },
    cashExpenses: 3187,
    totalSale: 4126,
    totalCash: 6746,
    cashInHand: 3559,
  },
  {
    date: "2026-01-22",
    openingCash: 3559,
    kitchenSale: 550,
    coffeeShop: 4146,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 672,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 1119,
    },
    cashExpenses: 1838,
    totalSale: 4696,
    totalCash: 8255,
    cashInHand: 6417,
  },
  {
    date: "2026-01-23",
    openingCash: 6417,
    kitchenSale: 500,
    coffeeShop: 4003,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 100,
      Egg: 230,
      "Milk/Curd/Paneer": 687,
      "Travel Expense": 2947,
    },
    cashExpenses: 3465,
    totalSale: 4503,
    totalCash: 10920,
    cashInHand: 7455,
  },
  {
    date: "2026-01-24",
    openingCash: 7455,
    kitchenSale: 560,
    coffeeShop: 3738,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 2210,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 90,
      "Travel Expense": 4590,
    },
    cashExpenses: 5333,
    totalSale: 4298,
    totalCash: 11753,
    cashInHand: 6420,
  },
  {
    date: "2026-01-25",
    openingCash: 6420,
    kitchenSale: 0,
    coffeeShop: 1727,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1700,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2412,
    },
    cashExpenses: 2867,
    totalSale: 1727,
    totalCash: 8147,
    cashInHand: 5280,
  },
  {
    date: "2026-01-26",
    openingCash: 5280,
    kitchenSale: 100,
    coffeeShop: 1478,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 250,
    advanceEntries: [
      {
        name: "Staff",
        amount: 250,
      },
    ],
    expenseEntries: {
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 687,
      "Travel Expense": 1047,
    },
    cashExpenses: 1546,
    totalSale: 1578,
    totalCash: 6858,
    cashInHand: 5312,
  },
  {
    date: "2026-01-27",
    openingCash: 5312,
    kitchenSale: 500,
    coffeeShop: 3227,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 600,
      Egg: 200,
      "Milk/Curd/Paneer": 828,
      "Travel Expense": 3558,
    },
    cashExpenses: 4128,
    totalSale: 3727,
    totalCash: 9039,
    cashInHand: 4911,
  },
  {
    date: "2026-01-28",
    openingCash: 4911,
    kitchenSale: 660,
    coffeeShop: 3941,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 2395,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 357,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 5159,
    },
    cashExpenses: 5839,
    totalSale: 4601,
    totalCash: 9512,
    cashInHand: 3673,
  },
  {
    date: "2026-01-29",
    openingCash: 3673,
    kitchenSale: 600,
    coffeeShop: 2780,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 690,
      "Travel Expense": 1020,
    },
    cashExpenses: 1623,
    totalSale: 3380,
    totalCash: 7053,
    cashInHand: 5430,
  },
  {
    date: "2026-01-30",
    openingCash: 5430,
    kitchenSale: 600,
    coffeeShop: 3220,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 80,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 2982,
    },
    cashExpenses: 3594,
    totalSale: 3820,
    totalCash: 9250,
    cashInHand: 5656,
  },
  {
    date: "2026-01-31",
    openingCash: 5656,
    kitchenSale: 700,
    coffeeShop: 3191,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1700,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 828,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 3050,
    },
    cashExpenses: 3700,
    totalSale: 3891,
    totalCash: 9547,
    cashInHand: 5847,
  },
  {
    date: "2026-02-01",
    openingCash: 5849,
    kitchenSale: 60,
    coffeeShop: 1394,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Veg/Fruit": 50,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 920,
    },
    cashExpenses: 1200,
    totalSale: 1454,
    totalCash: 7303,
    cashInHand: 6103,
  },
  {
    date: "2026-02-02",
    openingCash: 6103,
    kitchenSale: 660,
    coffeeShop: 3611,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 200,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1800,
      "Veg/Fruit": 3640,
      "Milk/Curd/Paneer": 612,
      "Travel Expense": 6052,
    },
    cashExpenses: 6482,
    totalSale: 4271,
    totalCash: 10374,
    cashInHand: 3892,
  },
  {
    date: "2026-02-03",
    openingCash: 3892,
    kitchenSale: 550,
    coffeeShop: 3258,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1800,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 564,
      "Mineral Water": 4400,
      "Travel Expense": 7469,
    },
    cashExpenses: 7879,
    totalSale: 3808,
    totalCash: 7700,
    cashInHand: -179,
  },
  {
    date: "2026-02-04",
    openingCash: -179,
    kitchenSale: 750,
    coffeeShop: 4241,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 200,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 707,
      Crockery: 120,
      "Travel Expense": 1107,
    },
    cashExpenses: 1662,
    totalSale: 4991,
    totalCash: 4812,
    cashInHand: 3150,
  },
  {
    date: "2026-02-05",
    openingCash: 3150,
    kitchenSale: 700,
    coffeeShop: 3452,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 121000,
    advanceEntries: [
      {
        name: "Staff",
        amount: 121000,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1800,
      "Veg/Fruit": 50,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 612,
      Conveyance: 200,
      "Travel Expense": 3022,
    },
    cashExpenses: 124608,
    totalSale: 4152,
    totalCash: 128302,
    cashInHand: 3694,
  },
  {
    date: "2026-02-06",
    openingCash: 3694,
    kitchenSale: 600,
    coffeeShop: 3675,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 40,
      "Milk/Curd/Paneer": 612,
      "Room Rent": 6000,
      "Travel Expense": 8682,
    },
    cashExpenses: 8987,
    totalSale: 4275,
    totalCash: 7969,
    cashInHand: -1018,
  },
  {
    date: "2026-02-07",
    openingCash: -1018,
    kitchenSale: 700,
    coffeeShop: 4095,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 605,
      "Travel Expense": 2685,
    },
    cashExpenses: 3353,
    totalSale: 4795,
    totalCash: 3777,
    cashInHand: 424,
  },
  {
    date: "2026-02-08",
    openingCash: 424,
    kitchenSale: 60,
    coffeeShop: 1631,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 930,
    },
    cashExpenses: 1210,
    totalSale: 1691,
    totalCash: 2115,
    cashInHand: 905,
  },
  {
    date: "2026-02-09",
    openingCash: 905,
    kitchenSale: 750,
    coffeeShop: 4738,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      Egg: 200,
      "Milk/Curd/Paneer": 605,
      "Travel Expense": 2835,
    },
    cashExpenses: 3260,
    totalSale: 5488,
    totalCash: 6393,
    cashInHand: 3133,
  },
  {
    date: "2026-02-10",
    openingCash: 3133,
    kitchenSale: 800,
    coffeeShop: 3626,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 2090,
      "Milk/Curd/Paneer": 510,
      Conveyance: 80,
      "Travel Expense": 4825,
    },
    cashExpenses: 5133,
    totalSale: 4426,
    totalCash: 7559,
    cashInHand: 2426,
  },
  {
    date: "2026-02-11",
    openingCash: 2426,
    kitchenSale: 700,
    coffeeShop: 4265,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 60,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 1160,
    },
    cashExpenses: 1940,
    totalSale: 4965,
    totalCash: 7391,
    cashInHand: 5451,
  },
  {
    date: "2026-02-12",
    openingCash: 5451,
    kitchenSale: 580,
    coffeeShop: 3689,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 2000,
      Ration: 300,
      "Milk/Curd/Paneer": 665,
      "Travel Expense": 4995,
    },
    cashExpenses: 5414,
    totalSale: 4269,
    totalCash: 9720,
    cashInHand: 4306,
  },
  {
    date: "2026-02-13",
    openingCash: 4306,
    kitchenSale: 500,
    coffeeShop: 3860,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1800,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2670,
    },
    cashExpenses: 3383,
    totalSale: 4360,
    totalCash: 8666,
    cashInHand: 5283,
  },
  {
    date: "2026-02-14",
    openingCash: 5283,
    kitchenSale: 480,
    coffeeShop: 3518,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 730,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 1137,
    },
    cashExpenses: 1872,
    totalSale: 3998,
    totalCash: 9281,
    cashInHand: 7409,
  },
  {
    date: "2026-02-15",
    openingCash: 7409,
    kitchenSale: 100,
    coffeeShop: 1536,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1800,
      "Veg/Fruit": 1795,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 4105,
    },
    cashExpenses: 4362,
    totalSale: 1636,
    totalCash: 9045,
    cashInHand: 4683,
  },
  {
    date: "2026-02-16",
    openingCash: 4683,
    kitchenSale: 750,
    coffeeShop: 4563,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 2960,
    },
    cashExpenses: 3768,
    totalSale: 5313,
    totalCash: 9996,
    cashInHand: 6228,
  },
  {
    date: "2026-02-17",
    openingCash: 6228,
    kitchenSale: 600,
    coffeeShop: 2782,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 40,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 2640,
    },
    cashExpenses: 2980,
    totalSale: 3382,
    totalCash: 9610,
    cashInHand: 6630,
  },
  {
    date: "2026-02-18",
    openingCash: 6630,
    kitchenSale: 800,
    coffeeShop: 4212,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 1595,
      Egg: 200,
      "Milk/Curd/Paneer": 600,
      "Travel Expense": 2395,
    },
    cashExpenses: 3110,
    totalSale: 5012,
    totalCash: 11642,
    cashInHand: 8532,
  },
  {
    date: "2026-02-19",
    openingCash: 8532,
    kitchenSale: 700,
    coffeeShop: 3396,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 300,
    advanceEntries: [
      {
        name: "Staff",
        amount: 300,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2705,
    },
    cashExpenses: 3360,
    totalSale: 4096,
    totalCash: 12628,
    cashInHand: 9268,
  },
  {
    date: "2026-02-20",
    openingCash: 9268,
    kitchenSale: 780,
    coffeeShop: 3511,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 1710,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 570,
      Conveyance: 200,
      "Travel Expense": 3070,
    },
    cashExpenses: 3563,
    totalSale: 4291,
    totalCash: 13559,
    cashInHand: 9996,
  },
  {
    date: "2026-02-21",
    openingCash: 9996,
    kitchenSale: 740,
    coffeeShop: 2600,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 666,
      "Travel Expense": 2756,
    },
    cashExpenses: 3139,
    totalSale: 3340,
    totalCash: 13336,
    cashInHand: 10197,
  },
  {
    date: "2026-02-22",
    openingCash: 10197,
    kitchenSale: 0,
    coffeeShop: 2325,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 1500,
    advanceEntries: [
      {
        name: "Staff",
        amount: 1500,
      },
    ],
    expenseEntries: {
      "Veg/Fruit": 2990,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 3500,
    },
    cashExpenses: 5163,
    totalSale: 2325,
    totalCash: 12522,
    cashInHand: 7359,
  },
  {
    date: "2026-02-23",
    openingCash: 7359,
    kitchenSale: 700,
    coffeeShop: 3392,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 50,
      Egg: 180,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2770,
    },
    cashExpenses: 3497,
    totalSale: 4092,
    totalCash: 11451,
    cashInHand: 7954,
  },
  {
    date: "2026-02-24",
    openingCash: 7954,
    kitchenSale: 800,
    coffeeShop: 3803,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 80,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 814,
      "Travel Expense": 1484,
    },
    cashExpenses: 2211,
    totalSale: 4603,
    totalCash: 12557,
    cashInHand: 10346,
  },
  {
    date: "2026-02-25",
    openingCash: 10346,
    kitchenSale: 740,
    coffeeShop: 4340,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 1065,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 3605,
    },
    cashExpenses: 4403,
    totalSale: 5080,
    totalCash: 15426,
    cashInHand: 11023,
  },
  {
    date: "2026-02-26",
    openingCash: 11023,
    kitchenSale: 700,
    coffeeShop: 3713,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "LPG/Fuel": 1800,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 510,
      "Sweet/Ice Cream": 117,
      "Travel Expense": 2477,
    },
    cashExpenses: 3796,
    totalSale: 4413,
    totalCash: 15436,
    cashInHand: 11640,
  },
  {
    date: "2026-02-27",
    openingCash: 11640,
    kitchenSale: 680,
    coffeeShop: 3421,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 200,
    advanceEntries: [
      {
        name: "Staff",
        amount: 200,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 50,
      "Bread/Butter": 360,
      Egg: 180,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 1330,
    },
    cashExpenses: 2285,
    totalSale: 4101,
    totalCash: 15741,
    cashInHand: 13456,
  },
  {
    date: "2026-02-28",
    openingCash: 13456,
    kitchenSale: 800,
    coffeeShop: 3250,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 110,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2650,
    },
    cashExpenses: 3199,
    totalSale: 4050,
    totalCash: 17506,
    cashInHand: 14307,
  },
  {
    date: "2026-03-01",
    openingCash: 0,
    kitchenSale: 0,
    coffeeShop: 0,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {},
    cashExpenses: 0,
    totalSale: 0,
    totalCash: 0,
    cashInHand: 0,
  },
  {
    date: "2026-03-02",
    openingCash: 0,
    kitchenSale: 0,
    coffeeShop: 0,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {},
    cashExpenses: 0,
    totalSale: 0,
    totalCash: 0,
    cashInHand: 0,
  },
  {
    date: "2026-03-03",
    openingCash: 0,
    kitchenSale: 0,
    coffeeShop: 0,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {},
    cashExpenses: 0,
    totalSale: 0,
    totalCash: 0,
    cashInHand: 0,
  },
  {
    date: "2026-03-01",
    openingCash: 14307,
    kitchenSale: 120,
    coffeeShop: 1615,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 1850,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 510,
      "Room Rent": 6000,
      "Travel Expense": 8720,
    },
    cashExpenses: 8783,
    totalSale: 1735,
    totalCash: 16042,
    cashInHand: 7259,
  },
  {
    date: "2026-03-02",
    openingCash: 7259,
    kitchenSale: 600,
    coffeeShop: 3245,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 2660,
    },
    cashExpenses: 3146,
    totalSale: 3845,
    totalCash: 11104,
    cashInHand: 7958,
  },
  {
    date: "2026-03-03",
    openingCash: 7958,
    kitchenSale: 450,
    coffeeShop: 2376,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 40,
      Egg: 180,
      "Milk/Curd/Paneer": 333,
      "Travel Expense": 553,
    },
    cashExpenses: 603,
    totalSale: 2826,
    totalCash: 10784,
    cashInHand: 10181,
  },
  {
    date: "2026-03-04",
    openingCash: 10181,
    kitchenSale: 0,
    coffeeShop: 891,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 78,
      "Travel Expense": 178,
    },
    cashExpenses: 293,
    totalSale: 891,
    totalCash: 11072,
    cashInHand: 10779,
  },
  {
    date: "2026-03-05",
    openingCash: 10779,
    kitchenSale: 200,
    coffeeShop: 2651,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1800,
      "Veg/Fruit": 1760,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 510,
      "Misc/Repair": 200,
      "Travel Expense": 4860,
    },
    cashExpenses: 5296,
    totalSale: 2851,
    totalCash: 13630,
    cashInHand: 8334,
  },
  {
    date: "2026-03-06",
    openingCash: 8334,
    kitchenSale: 1000,
    coffeeShop: 3164,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 588,
      "Travel Expense": 898,
    },
    cashExpenses: 1558,
    totalSale: 4164,
    totalCash: 12498,
    cashInHand: 10940,
  },
  {
    date: "2026-03-07",
    openingCash: 10940,
    kitchenSale: 800,
    coffeeShop: 2901,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1900,
      "Veg/Fruit": 2815,
      "Milk/Curd/Paneer": 588,
      "Travel Expense": 5303,
    },
    cashExpenses: 5896,
    totalSale: 3701,
    totalCash: 14641,
    cashInHand: 8745,
  },
  {
    date: "2026-03-08",
    openingCash: 8745,
    kitchenSale: 160,
    coffeeShop: 1588,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 40,
      "Bread/Butter": 360,
      Egg: 180,
      "Milk/Curd/Paneer": 285,
      "Travel Expense": 865,
    },
    cashExpenses: 905,
    totalSale: 1748,
    totalCash: 10493,
    cashInHand: 9588,
  },
  {
    date: "2026-03-09",
    openingCash: 9588,
    kitchenSale: 700,
    coffeeShop: 3713,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1900,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 730,
      "Travel Expense": 2920,
    },
    cashExpenses: 3639,
    totalSale: 4413,
    totalCash: 14001,
    cashInHand: 10362,
  },
  {
    date: "2026-03-10",
    openingCash: 10362,
    kitchenSale: 750,
    coffeeShop: 3138,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1900,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 588,
      "Travel Expense": 2548,
    },
    cashExpenses: 2764,
    totalSale: 3888,
    totalCash: 14250,
    cashInHand: 11486,
  },
  {
    date: "2026-03-11",
    openingCash: 11486,
    kitchenSale: 680,
    coffeeShop: 3384,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 1783,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2523,
    },
    cashExpenses: 2978,
    totalSale: 4064,
    totalCash: 15550,
    cashInHand: 12572,
  },
  {
    date: "2026-03-12",
    openingCash: 12572,
    kitchenSale: 740,
    coffeeShop: 3344,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 1200,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2000,
    },
    cashExpenses: 2641,
    totalSale: 4084,
    totalCash: 16656,
    cashInHand: 14015,
  },
  {
    date: "2026-03-13",
    openingCash: 14015,
    kitchenSale: 700,
    coffeeShop: 3493,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1900,
      "Veg/Fruit": 2815,
      "Bread/Butter": 360,
      Egg: 180,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 6110,
    },
    cashExpenses: 6916,
    totalSale: 4193,
    totalCash: 18208,
    cashInHand: 11292,
  },
  {
    date: "2026-03-14",
    openingCash: 11292,
    kitchenSale: 700,
    coffeeShop: 3266,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 670,
      "Travel Expense": 1075,
    },
    cashExpenses: 1801,
    totalSale: 3966,
    totalCash: 15258,
    cashInHand: 13457,
  },
  {
    date: "2026-03-15",
    openingCash: 13457,
    kitchenSale: 180,
    coffeeShop: 2186,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1200,
      "Veg/Fruit": 260,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 1970,
    },
    cashExpenses: 2340,
    totalSale: 2366,
    totalCash: 15823,
    cashInHand: 13483,
  },
  {
    date: "2026-03-16",
    openingCash: 13483,
    kitchenSale: 900,
    coffeeShop: 3305,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "Veg/Fruit": 1825,
      "Milk/Curd/Paneer": 510,
      "Mineral Water": 5500,
      "Travel Expense": 8180,
    },
    cashExpenses: 8686,
    totalSale: 4205,
    totalCash: 17688,
    cashInHand: 9002,
  },
  {
    date: "2026-03-17",
    openingCash: 9002,
    kitchenSale: 800,
    coffeeShop: 3351,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1400,
      "Veg/Fruit": 26014,
      Egg: 180,
      "Milk/Curd/Paneer": 570,
      "Mineral Water": 140,
      "Travel Expense": 28304,
    },
    cashExpenses: 28799,
    totalSale: 4151,
    totalCash: 38153,
    cashInHand: 9354,
  },
  {
    date: "2026-03-18",
    openingCash: 9354,
    kitchenSale: 960,
    coffeeShop: 3781,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1400,
      "Veg/Fruit": 60,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 255,
      "Sweet/Ice Cream": 2236,
      "Travel Expense": 4311,
    },
    cashExpenses: 4566,
    totalSale: 4741,
    totalCash: 14095,
    cashInHand: 9529,
  },
  {
    date: "2026-03-19",
    openingCash: 9529,
    kitchenSale: 750,
    coffeeShop: 2723,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 1400,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2305,
    },
    cashExpenses: 2675,
    totalSale: 3473,
    totalCash: 13002,
    cashInHand: 10327,
  },
  {
    date: "2026-03-20",
    openingCash: 10327,
    kitchenSale: 700,
    coffeeShop: 3512,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1500,
      "Veg/Fruit": 3825,
      "Milk/Curd/Paneer": 595,
      Conveyance: 200,
      "Travel Expense": 6120,
    },
    cashExpenses: 6740,
    totalSale: 4212,
    totalCash: 14539,
    cashInHand: 7799,
  },
  {
    date: "2026-03-21",
    openingCash: 7799,
    kitchenSale: 760,
    coffeeShop: 3418,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 100,
    advanceEntries: [
      {
        name: "Staff",
        amount: 100,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 50,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 648,
      "Travel Expense": 1288,
    },
    cashExpenses: 1388,
    totalSale: 4178,
    totalCash: 11977,
    cashInHand: 10589,
  },
  {
    date: "2026-03-22",
    openingCash: 10589,
    kitchenSale: 120,
    coffeeShop: 1189,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 1500,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 2070,
    },
    cashExpenses: 3025,
    totalSale: 1309,
    totalCash: 11898,
    cashInHand: 8873,
  },
  {
    date: "2026-03-23",
    openingCash: 8873,
    kitchenSale: 850,
    coffeeShop: 2853,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 300,
    advanceEntries: [
      {
        name: "Staff",
        amount: 300,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2000,
      "Veg/Fruit": 1830,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 666,
      "Travel Expense": 5086,
    },
    cashExpenses: 5961,
    totalSale: 3703,
    totalCash: 12576,
    cashInHand: 6615,
  },
  {
    date: "2026-03-24",
    openingCash: 6615,
    kitchenSale: 800,
    coffeeShop: 2778,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 240,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 980,
    },
    cashExpenses: 1505,
    totalSale: 3578,
    totalCash: 10193,
    cashInHand: 8688,
  },
  {
    date: "2026-03-25",
    openingCash: 8688,
    kitchenSale: 600,
    coffeeShop: 2837,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 3270,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 3780,
    },
    cashExpenses: 4200,
    totalSale: 3437,
    totalCash: 12125,
    cashInHand: 7925,
  },
  {
    date: "2026-03-26",
    openingCash: 7925,
    kitchenSale: 660,
    coffeeShop: 2146,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2200,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 3000,
    },
    cashExpenses: 3245,
    totalSale: 2806,
    totalCash: 10731,
    cashInHand: 7486,
  },
  {
    date: "2026-03-27",
    openingCash: 7486,
    kitchenSale: 500,
    coffeeShop: 2667,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 255,
      "Travel Expense": 535,
    },
    cashExpenses: 935,
    totalSale: 3167,
    totalCash: 10653,
    cashInHand: 9718,
  },
  {
    date: "2026-03-28",
    openingCash: 9718,
    kitchenSale: 400,
    coffeeShop: 2497,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2300,
      "Milk/Curd/Paneer": 315,
      "Travel Expense": 2845,
    },
    cashExpenses: 3505,
    totalSale: 2897,
    totalCash: 12615,
    cashInHand: 9110,
  },
  {
    date: "2026-03-29",
    openingCash: 9110,
    kitchenSale: 0,
    coffeeShop: 1997,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Veg/Fruit": 1900,
      "Milk/Curd/Paneer": 255,
      "Misc/Repair": 960,
      "Travel Expense": 3345,
    },
    cashExpenses: 3570,
    totalSale: 1997,
    totalCash: 11107,
    cashInHand: 7537,
  },
  {
    date: "2026-03-30",
    openingCash: 7537,
    kitchenSale: 580,
    coffeeShop: 3399,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 345,
      "LPG/Fuel": 2300,
      "Bread/Butter": 418,
      "Milk/Curd/Paneer": 411,
      "Travel Expense": 3474,
    },
    cashExpenses: 4049,
    totalSale: 3979,
    totalCash: 11516,
    cashInHand: 7467,
  },
  {
    date: "2026-03-31",
    openingCash: 7467,
    kitchenSale: 700,
    coffeeShop: 2508,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2300,
      "Milk/Curd/Paneer": 333,
      "Travel Expense": 2863,
    },
    cashExpenses: 3303,
    totalSale: 3208,
    totalCash: 10675,
    cashInHand: 7372,
  },
  {
    date: "2026-04-01",
    openingCash: 7372,
    kitchenSale: 600,
    coffeeShop: 3523,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "Milk/Curd/Paneer": 315,
      "Room Rent": 6000,
      "Travel Expense": 6545,
    },
    cashExpenses: 6980,
    totalSale: 4123,
    totalCash: 11495,
    cashInHand: 4515,
  },
  {
    date: "2026-04-02",
    openingCash: 4515,
    kitchenSale: 650,
    coffeeShop: 3264,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2300,
      Egg: 160,
      "Milk/Curd/Paneer": 315,
      "Travel Expense": 3005,
    },
    cashExpenses: 3910,
    totalSale: 3914,
    totalCash: 8429,
    cashInHand: 4519,
  },
  {
    date: "2026-04-03",
    openingCash: 4519,
    kitchenSale: 600,
    coffeeShop: 3315,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 230,
      "LPG/Fuel": 2100,
      "Veg/Fruit": 1860,
      "Milk/Curd/Paneer": 666,
      Conveyance: 3000,
      "Travel Expense": 7856,
    },
    cashExpenses: 8576,
    totalSale: 3915,
    totalCash: 8434,
    cashInHand: -142,
  },
  {
    date: "2026-04-04",
    openingCash: -142,
    kitchenSale: 400,
    coffeeShop: 2909,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 930,
    },
    cashExpenses: 1500,
    totalSale: 3309,
    totalCash: 3167,
    cashInHand: 1667,
  },
  {
    date: "2026-04-05",
    openingCash: 1667,
    kitchenSale: 0,
    coffeeShop: 1384,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 50,
      "Milk/Curd/Paneer": 255,
      Paneer: 78,
      "Travel Expense": 383,
    },
    cashExpenses: 638,
    totalSale: 1384,
    totalCash: 3051,
    cashInHand: 2413,
  },
  {
    date: "2026-04-06",
    openingCash: 2413,
    kitchenSale: 600,
    coffeeShop: 3856,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2130,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 255,
      "Sweet/Ice Cream": 3745,
      "Travel Expense": 6430,
    },
    cashExpenses: 7085,
    totalSale: 4456,
    totalCash: 6869,
    cashInHand: -216,
  },
  {
    date: "2026-04-07",
    openingCash: -216,
    kitchenSale: 780,
    coffeeShop: 3836,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 100,
      Egg: 160,
      "Milk/Curd/Paneer": 315,
      "Travel Expense": 815,
    },
    cashExpenses: 1445,
    totalSale: 4616,
    totalCash: 4400,
    cashInHand: 2955,
  },
  {
    date: "2026-04-08",
    openingCash: 2955,
    kitchenSale: 800,
    coffeeShop: 3648,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 2697,
      Ration: 320,
      "Milk/Curd/Paneer": 255,
      "Travel Expense": 3632,
    },
    cashExpenses: 4387,
    totalSale: 4448,
    totalCash: 7403,
    cashInHand: 3016,
  },
  {
    date: "2026-04-09",
    openingCash: 3016,
    kitchenSale: 780,
    coffeeShop: 3624,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2500,
      Ration: 320,
      "Milk/Curd/Paneer": 315,
      "Travel Expense": 3375,
    },
    cashExpenses: 4220,
    totalSale: 4404,
    totalCash: 7420,
    cashInHand: 3200,
  },
  {
    date: "2026-04-10",
    openingCash: 3200,
    kitchenSale: 650,
    coffeeShop: 5158,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 600,
      "Veg/Fruit": 1355,
      "Milk/Curd/Paneer": 255,
      "Travel Expense": 2210,
    },
    cashExpenses: 2940,
    totalSale: 5808,
    totalCash: 9008,
    cashInHand: 6068,
  },
  {
    date: "2026-04-11",
    openingCash: 6068,
    kitchenSale: 780,
    coffeeShop: 4814,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2130,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 255,
      Paneer: 180,
      "Travel Expense": 2905,
    },
    cashExpenses: 3435,
    totalSale: 5594,
    totalCash: 11662,
    cashInHand: 8227,
  },
  {
    date: "2026-04-12",
    openingCash: 8227,
    kitchenSale: 120,
    coffeeShop: 3363,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 100,
      "Bread/Butter": 360,
      Egg: 170,
      "Milk/Curd/Paneer": 255,
      Paneer: 85,
      "Travel Expense": 970,
    },
    cashExpenses: 1585,
    totalSale: 3483,
    totalCash: 11710,
    cashInHand: 10125,
  },
  {
    date: "2026-04-13",
    openingCash: 10125,
    kitchenSale: 750,
    coffeeShop: 5467,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2130,
      "Veg/Fruit": 100,
      "Bread/Butter": 240,
      "Milk/Curd/Paneer": 570,
      Paneer: 80,
      "Travel Expense": 3360,
    },
    cashExpenses: 3920,
    totalSale: 6217,
    totalCash: 16342,
    cashInHand: 12422,
  },
  {
    date: "2026-04-14",
    openingCash: 12422,
    kitchenSale: 780,
    coffeeShop: 5495,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 150,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 510,
      "Travel Expense": 1100,
    },
    cashExpenses: 1840,
    totalSale: 6275,
    totalCash: 18697,
    cashInHand: 16857,
  },
  {
    date: "2026-04-15",
    openingCash: 16857,
    kitchenSale: 700,
    coffeeShop: 5047,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 150,
      "Milk/Curd/Paneer": 510,
      Paneer: 180,
      Conveyance: 200,
      "Travel Expense": 3600,
    },
    cashExpenses: 4460,
    totalSale: 5747,
    totalCash: 22604,
    cashInHand: 18144,
  },
  {
    date: "2026-04-16",
    openingCash: 18144,
    kitchenSale: 650,
    coffeeShop: 6078,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 1930,
      "Milk/Curd/Paneer": 510,
      Paneer: 234,
      Conveyance: 100,
      "Travel Expense": 3134,
    },
    cashExpenses: 4229,
    totalSale: 6728,
    totalCash: 24872,
    cashInHand: 20643,
  },
  {
    date: "2026-04-17",
    openingCash: 20643,
    kitchenSale: 600,
    coffeeShop: 3862,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 100,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 3430,
    },
    cashExpenses: 4215,
    totalSale: 4462,
    totalCash: 25105,
    cashInHand: 20890,
  },
  {
    date: "2026-04-18",
    openingCash: 20890,
    kitchenSale: 540,
    coffeeShop: 3491,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 200,
      Egg: 180,
      "Milk/Curd/Paneer": 510,
      Paneer: 180,
      "Misc/Repair": 260,
      "Travel Expense": 3890,
    },
    cashExpenses: 4764,
    totalSale: 4031,
    totalCash: 24921,
    cashInHand: 20157,
  },
  {
    date: "2026-04-19",
    openingCash: 20157,
    kitchenSale: 100,
    coffeeShop: 2004,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 2200,
      "Veg/Fruit": 100,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 560,
      "Travel Expense": 3220,
    },
    cashExpenses: 3220,
    totalSale: 2104,
    totalCash: 22261,
    cashInHand: 19041,
  },
  {
    date: "2026-04-20",
    openingCash: 19041,
    kitchenSale: 0,
    coffeeShop: 5975,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 500,
      "LPG/Fuel": 2200,
      "Bread/Butter": 240,
      Ration: 928,
      "Milk/Curd/Paneer": 510,
      Paneer: 1960,
      "Sweet/Ice Cream": 2530,
      "Misc/Repair": 2500,
      "Travel Expense": 11368,
    },
    cashExpenses: 11879,
    totalSale: 5975,
    totalCash: 25016,
    cashInHand: 13137,
  },
  {
    date: "2026-04-21",
    openingCash: 13137,
    kitchenSale: 500,
    coffeeShop: 3795,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 600,
    advanceEntries: [
      {
        name: "Staff",
        amount: 600,
      },
    ],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 3070,
      "Bread/Butter": 360,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 6560,
    },
    cashExpenses: 7710,
    totalSale: 4295,
    totalCash: 17432,
    cashInHand: 9722,
  },
  {
    date: "2026-04-22",
    openingCash: 9722,
    kitchenSale: 600,
    coffeeShop: 3460,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 510,
      Paneer: 85,
      "Sweet/Ice Cream": 2604,
      "Travel Expense": 3619,
    },
    cashExpenses: 4364,
    totalSale: 4060,
    totalCash: 13782,
    cashInHand: 9418,
  },
  {
    date: "2026-04-23",
    openingCash: 9418,
    kitchenSale: 660,
    coffeeShop: 3959,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 2200,
      "Veg/Fruit": 50,
      "Bread/Butter": 200,
      Egg: 180,
      "Milk/Curd/Paneer": 510,
      Conveyance: 500,
      "Travel Expense": 3640,
    },
    cashExpenses: 4125,
    totalSale: 4619,
    totalCash: 14037,
    cashInHand: 9912,
  },
  {
    date: "2026-04-24",
    openingCash: 9912,
    kitchenSale: 580,
    coffeeShop: 3360,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 1545,
      "Milk/Curd/Paneer": 570,
      Paneer: 80,
      "Mineral Water": 4894,
      "Travel Expense": 9529,
    },
    cashExpenses: 9859,
    totalSale: 3940,
    totalCash: 13852,
    cashInHand: 3993,
  },
  {
    date: "2026-04-25",
    openingCash: 3993,
    kitchenSale: 600,
    coffeeShop: 3736,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 40,
      "Milk/Curd/Paneer": 510,
      Paneer: 80,
      "Travel Expense": 3070,
    },
    cashExpenses: 3830,
    totalSale: 4336,
    totalCash: 8329,
    cashInHand: 4499,
  },
  {
    date: "2026-04-26",
    openingCash: 4499,
    kitchenSale: 0,
    coffeeShop: 1925,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 40,
      "Milk/Curd/Paneer": 255,
      "Travel Expense": 295,
    },
    cashExpenses: 415,
    totalSale: 1925,
    totalCash: 6424,
    cashInHand: 6009,
  },
  {
    date: "2026-04-27",
    openingCash: 6009,
    kitchenSale: 460,
    coffeeShop: 3400,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 1650,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 570,
      "Travel Expense": 4860,
    },
    cashExpenses: 5340,
    totalSale: 3860,
    totalCash: 9869,
    cashInHand: 4529,
  },
  {
    date: "2026-04-28",
    openingCash: 4529,
    kitchenSale: 520,
    coffeeShop: 4390,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 504,
      Paneer: 160,
      "Sweet/Ice Cream": 2222,
      "Travel Expense": 3186,
    },
    cashExpenses: 3596,
    totalSale: 4910,
    totalCash: 9439,
    cashInHand: 5843,
  },
  {
    date: "2026-04-29",
    openingCash: 5843,
    kitchenSale: 600,
    coffeeShop: 3803,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 2200,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 408,
      Paneer: 80,
      "Travel Expense": 3108,
    },
    cashExpenses: 3698,
    totalSale: 4403,
    totalCash: 10246,
    cashInHand: 6548,
  },
  {
    date: "2026-04-30",
    openingCash: 6548,
    kitchenSale: 600,
    coffeeShop: 4974,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 350,
      Egg: 180,
      "Milk/Curd/Paneer": 408,
      Conveyance: 200,
      "Travel Expense": 1498,
    },
    cashExpenses: 2578,
    totalSale: 5574,
    totalCash: 12122,
    cashInHand: 9544,
  },
  {
    date: "2026-05-01",
    openingCash: 0,
    kitchenSale: 0,
    coffeeShop: 0,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {},
    cashExpenses: 0,
    totalSale: 0,
    totalCash: 0,
    cashInHand: 0,
  },
  {
    date: "2026-05-01",
    openingCash: 9494,
    kitchenSale: 540,
    coffeeShop: 3293,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 1770,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 468,
      "Travel Expense": 5878,
    },
    cashExpenses: 6878,
    totalSale: 3833,
    totalCash: 13327,
    cashInHand: 6449,
  },
  {
    date: "2026-05-02",
    openingCash: 6449,
    kitchenSale: 600,
    coffeeShop: 4215,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 468,
      "Room Rent": 6000,
      "Misc/Repair": 80,
      "Travel Expense": 6608,
    },
    cashExpenses: 7328,
    totalSale: 4815,
    totalCash: 11264,
    cashInHand: 3936,
  },
  {
    date: "2026-05-03",
    openingCash: 3936,
    kitchenSale: 120,
    coffeeShop: 2053,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 408,
      Conveyance: 100,
      "Travel Expense": 608,
    },
    cashExpenses: 938,
    totalSale: 2173,
    totalCash: 6109,
    cashInHand: 5171,
  },
  {
    date: "2026-05-04",
    openingCash: 5171,
    kitchenSale: 700,
    coffeeShop: 2950,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "Veg/Fruit": 2305,
      "Milk/Curd/Paneer": 408,
      "Misc/Repair": 80,
      Conveyance: 200,
      "Travel Expense": 3353,
    },
    cashExpenses: 4023,
    totalSale: 3650,
    totalCash: 8821,
    cashInHand: 4798,
  },
  {
    date: "2026-05-05",
    openingCash: 4798,
    kitchenSale: 650,
    coffeeShop: 3459,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 3200,
      "Veg/Fruit": 60,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 468,
      Paneer: 160,
      "Travel Expense": 4088,
    },
    cashExpenses: 4708,
    totalSale: 4109,
    totalCash: 8907,
    cashInHand: 4199,
  },
  {
    date: "2026-05-06",
    openingCash: 4199,
    kitchenSale: 550,
    coffeeShop: 3456,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 60,
      "Bread/Butter": 60,
      Egg: 180,
      "Milk/Curd/Paneer": 408,
      "Travel Expense": 948,
    },
    cashExpenses: 1753,
    totalSale: 4006,
    totalCash: 8205,
    cashInHand: 6452,
  },
  {
    date: "2026-05-07",
    openingCash: 6452,
    kitchenSale: 700,
    coffeeShop: 3663,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 60,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 504,
      "Travel Expense": 4204,
    },
    cashExpenses: 5024,
    totalSale: 4363,
    totalCash: 10815,
    cashInHand: 5791,
  },
  {
    date: "2026-05-08",
    openingCash: 5791,
    kitchenSale: 600,
    coffeeShop: 3340,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 1861,
      "Milk/Curd/Paneer": 408,
      "Travel Expense": 2509,
    },
    cashExpenses: 3034,
    totalSale: 3940,
    totalCash: 9731,
    cashInHand: 6697,
  },
  {
    date: "2026-05-09",
    openingCash: 6697,
    kitchenSale: 680,
    coffeeShop: 2714,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 360,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 60,
      "Bread/Butter": 180,
      "Milk/Curd/Paneer": 408,
      "Travel Expense": 4208,
    },
    cashExpenses: 4783,
    totalSale: 3394,
    totalCash: 10091,
    cashInHand: 5308,
  },
  {
    date: "2026-05-10",
    openingCash: 5308,
    kitchenSale: 0,
    coffeeShop: 1415,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 60,
      "Bread/Butter": 60,
      "Milk/Curd/Paneer": 408,
      Paneer: 162,
      Conveyance: 200,
      "Travel Expense": 1130,
    },
    cashExpenses: 1190,
    totalSale: 1415,
    totalCash: 6723,
    cashInHand: 5533,
  },
  {
    date: "2026-05-11",
    openingCash: 5533,
    kitchenSale: 750,
    coffeeShop: 3108,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 3200,
      "Veg/Fruit": 100,
      Egg: 180,
      "Milk/Curd/Paneer": 468,
      "Travel Expense": 3948,
    },
    cashExpenses: 4408,
    totalSale: 3858,
    totalCash: 9391,
    cashInHand: 4983,
  },
  {
    date: "2026-05-12",
    openingCash: 4983,
    kitchenSale: 600,
    coffeeShop: 2883,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 468,
      "Travel Expense": 788,
    },
    cashExpenses: 1303,
    totalSale: 3483,
    totalCash: 8466,
    cashInHand: 7163,
  },
  {
    date: "2026-05-13",
    openingCash: 7163,
    kitchenSale: 700,
    coffeeShop: 4447,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 2070,
      "Bread/Butter": 200,
      "Milk/Curd/Paneer": 408,
      "Sweet/Ice Cream": 2370,
      "Travel Expense": 5288,
    },
    cashExpenses: 5773,
    totalSale: 5147,
    totalCash: 12310,
    cashInHand: 6537,
  },
  {
    date: "2026-05-14",
    openingCash: 6537,
    kitchenSale: 750,
    coffeeShop: 4178,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 50,
      Egg: 180,
      "Milk/Curd/Paneer": 408,
      "Mineral Water": 4894,
      "Travel Expense": 8972,
    },
    cashExpenses: 9772,
    totalSale: 4928,
    totalCash: 11465,
    cashInHand: 1693,
  },
  {
    date: "2026-05-15",
    openingCash: 1693,
    kitchenSale: 600,
    coffeeShop: 3917,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Bread/Butter": 150,
      "Milk/Curd/Paneer": 468,
      "Travel Expense": 4058,
    },
    cashExpenses: 4698,
    totalSale: 4517,
    totalCash: 6210,
    cashInHand: 1512,
  },
  {
    date: "2026-05-16",
    openingCash: 1512,
    kitchenSale: 700,
    coffeeShop: 4469,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 60,
      "Bread/Butter": 45,
      "Milk/Curd/Paneer": 468,
      Paneer: 160,
      "Travel Expense": 4173,
    },
    cashExpenses: 5178,
    totalSale: 5169,
    totalCash: 6681,
    cashInHand: 1503,
  },
  {
    date: "2026-05-17",
    openingCash: 1503,
    kitchenSale: 160,
    coffeeShop: 3080,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 80,
      "Bread/Butter": 200,
      Egg: 180,
      "Milk/Curd/Paneer": 468,
      "Travel Expense": 928,
    },
    cashExpenses: 1718,
    totalSale: 3240,
    totalCash: 4743,
    cashInHand: 3025,
  },
  {
    date: "2026-05-18",
    openingCash: 3025,
    kitchenSale: 700,
    coffeeShop: 3314,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 340,
      "Veg/Fruit": 80,
      "Milk/Curd/Paneer": 432,
      Paneer: 255,
      "Travel Expense": 1107,
    },
    cashExpenses: 2207,
    totalSale: 4014,
    totalCash: 7039,
    cashInHand: 4832,
  },
  {
    date: "2026-05-19",
    openingCash: 4832,
    kitchenSale: 650,
    coffeeShop: 4419,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Bread/Butter": 180,
      "Milk/Curd/Paneer": 432,
      "Travel Expense": 4052,
    },
    cashExpenses: 5032,
    totalSale: 5069,
    totalCash: 9901,
    cashInHand: 4869,
  },
  {
    date: "2026-05-20",
    openingCash: 4869,
    kitchenSale: 750,
    coffeeShop: 4370,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 2255,
      "Bread/Butter": 90,
      "Milk/Curd/Paneer": 432,
      "Travel Expense": 2777,
    },
    cashExpenses: 3902,
    totalSale: 5120,
    totalCash: 9989,
    cashInHand: 6087,
  },
  {
    date: "2026-05-21",
    openingCash: 6087,
    kitchenSale: 700,
    coffeeShop: 4308,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Bread/Butter": 80,
      "Milk/Curd/Paneer": 492,
      "Travel Expense": 4012,
    },
    cashExpenses: 5067,
    totalSale: 5008,
    totalCash: 11095,
    cashInHand: 6028,
  },
  {
    date: "2026-05-22",
    openingCash: 6028,
    kitchenSale: 600,
    coffeeShop: 4156,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 80,
      "Bread/Butter": 180,
      "Milk/Curd/Paneer": 492,
      "Misc/Repair": 80,
      "Travel Expense": 1072,
    },
    cashExpenses: 2087,
    totalSale: 4756,
    totalCash: 10784,
    cashInHand: 8697,
  },
  {
    date: "2026-05-23",
    openingCash: 8697,
    kitchenSale: 550,
    coffeeShop: 4509,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 120,
      "LPG/Fuel": 3200,
      Egg: 180,
      "Milk/Curd/Paneer": 432,
      Paneer: 180,
      "Sweet/Ice Cream": 2667,
      "Travel Expense": 6779,
    },
    cashExpenses: 7639,
    totalSale: 5059,
    totalCash: 13756,
    cashInHand: 6117,
  },
  {
    date: "2026-05-24",
    openingCash: 6117,
    kitchenSale: 0,
    coffeeShop: 2450,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 60,
      "Bread/Butter": 180,
      "Milk/Curd/Paneer": 492,
      "Travel Expense": 732,
    },
    cashExpenses: 1357,
    totalSale: 2450,
    totalCash: 8567,
    cashInHand: 7210,
  },
  {
    date: "2026-05-25",
    openingCash: 7210,
    kitchenSale: 700,
    coffeeShop: 4203,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 3200,
      "Veg/Fruit": 40,
      "Bread/Butter": 1375,
      "Milk/Curd/Paneer": 492,
      Paneer: 90,
      "Travel Expense": 5197,
    },
    cashExpenses: 5967,
    totalSale: 4903,
    totalCash: 12113,
    cashInHand: 6146,
  },
  {
    date: "2026-05-26",
    openingCash: 6146,
    kitchenSale: 800,
    coffeeShop: 3575,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 2380,
      "Milk/Curd/Paneer": 432,
      Conveyance: 200,
      "Travel Expense": 3252,
    },
    cashExpenses: 3957,
    totalSale: 4375,
    totalCash: 10521,
    cashInHand: 6564,
  },
  {
    date: "2026-05-27",
    openingCash: 6564,
    kitchenSale: 550,
    coffeeShop: 2924,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 100,
      "Milk/Curd/Paneer": 492,
      Conveyance: 100,
      "Travel Expense": 4132,
    },
    cashExpenses: 5072,
    totalSale: 3474,
    totalCash: 10038,
    cashInHand: 4966,
  },
  {
    date: "2026-05-28",
    openingCash: 4966,
    kitchenSale: 800,
    coffeeShop: 3396,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "LPG/Fuel": 3200,
      "Veg/Fruit": 60,
      Egg: 180,
      "Milk/Curd/Paneer": 432,
      "Travel Expense": 3872,
    },
    cashExpenses: 4587,
    totalSale: 4196,
    totalCash: 9162,
    cashInHand: 4575,
  },
  {
    date: "2026-05-29",
    openingCash: 4575,
    kitchenSale: 600,
    coffeeShop: 3292,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 432,
      Conveyance: 300,
      "Travel Expense": 1032,
    },
    cashExpenses: 1982,
    totalSale: 3892,
    totalCash: 8467,
    cashInHand: 6485,
  },
  {
    date: "2026-05-30",
    openingCash: 6485,
    kitchenSale: 600,
    coffeeShop: 4493,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Bakery Snacks": 240,
      "LPG/Fuel": 3200,
      "Veg/Fruit": 100,
      "Bread/Butter": 90,
      "Milk/Curd/Paneer": 60,
      Paneer: 170,
      "Travel Expense": 3860,
    },
    cashExpenses: 4825,
    totalSale: 5093,
    totalCash: 11578,
    cashInHand: 6753,
  },
  {
    date: "2026-05-31",
    openingCash: 6753,
    kitchenSale: 0,
    coffeeShop: 2531,
    officialCr: 0,
    officialCrEntries: [],
    personalCr: 0,
    personalCrEntries: [],
    upiReceived: 0,
    cashToOffice: 0,
    salary: 0,
    salaryEntries: [],
    advance: 0,
    advanceEntries: [],
    expenseEntries: {
      "Veg/Fruit": 60,
      "Milk/Curd/Paneer": 432,
      Paneer: 90,
      "Travel Expense": 582,
    },
    cashExpenses: 777,
    totalSale: 2531,
    totalCash: 9284,
    cashInHand: 8507,
  },
];

const partnerTxnsByName = {
  "Vijayant Kohli": [
    {
      date: "2026-01-01",
      type: "receive",
      amount: 10000,
      note: "Cash received (daybook)",
    },
    {
      date: "2026-01-03",
      type: "receive",
      amount: 116600,
      note: "Cash received (daybook)",
    },
    {
      date: "2026-02-05",
      type: "receive",
      amount: 121000,
      note: "Cash received (daybook)",
    },
    {
      date: "2026-03-17",
      type: "receive",
      amount: 25000,
      note: "Cash received (daybook)",
    },
  ],
};

const buildEntry = (raw) => {
  const kitchenSale = raw.kitchenSale;
  const coffeeShop = raw.coffeeShop;

  return {
    date: raw.date,
    shop: SHOP_ID,

    openingCash: raw.openingCash,

    kitchenSale,
    kitchenSubTabs: [
      { name: "Kitchen Sale", entries: [], directAmount: kitchenSale },
    ],
    kitchenSaleEntries: [],

    coffeeShop,
    coffeeShopSale: coffeeShop,
    coffeeSubTabs: [
      { name: "Coffee Shop", entries: [], directAmount: coffeeShop },
    ],
    coffeeShopEntries: [],

    officialCr: raw.officialCr,
    officialCrEntries: raw.officialCrEntries,
    personalCr: raw.personalCr,
    personalCrEntries: raw.personalCrEntries,

    upiReceived: raw.upiReceived,

    cafeSale: 0,
    cafeNight: 0,

    totalSale: raw.totalSale,
    totalCash: raw.totalCash,

    cashToOffice: raw.cashToOffice,
    cashToOfficeEntries: [],

    salary: raw.salary,
    salaryEntries: raw.salaryEntries,
    advance: raw.advance,
    advanceEntries: raw.advanceEntries,

    expenseEntries: raw.expenseEntries,
    cashExpenses: raw.cashExpenses,

    cashInHand: raw.cashInHand,
    closingCash: raw.cashInHand,
  };
};

const run = async () => {
  await connectDB();

  try {
    const deletedDaybook = await DayBook.deleteMany({
      shop: SHOP_ID,
      date: { $gte: RANGE_START, $lt: RANGE_END },
    });
    console.log(
      `Deleted ${deletedDaybook.deletedCount} existing daybook entries for Metro Hospital, Haridwar`,
    );

    // Remove duplicate dates from the source data.
    // Some dates contain an empty/placeholder record followed by
    // the actual financial record.
    //
    // Keep the LAST occurrence of each date.

    const uniqueEntries = Array.from(
      new Map(rawEntries.map((entry) => [entry.date, entry])).values(),
    );

    console.log(`Source entries: ${rawEntries.length}`);
    console.log(`Unique entries: ${uniqueEntries.length}`);

    const docs = uniqueEntries.map(buildEntry);

    const result = await DayBook.insertMany(docs, {
      ordered: true,
    });

    console.log(
      `Inserted ${result.length} daybook entries for Metro Hospital, Haridwar`,
    );

    // Ensure partners exist, then reseed their transactions for this shop + range
    const partnerNames = Object.keys(partnerTxnsByName);
    const partnerMap = {};
    for (const name of partnerNames) {
      let partner = await Partner.findOne({ name });
      if (!partner) partner = await Partner.create({ name });
      partnerMap[name] = partner._id;
    }

    const deletedTxns = await PartnerTransaction.deleteMany({
      shop: SHOP_ID,
      partner: { $in: Object.values(partnerMap) },
      date: { $gte: RANGE_START, $lt: RANGE_END },
    });
    console.log(
      `Deleted ${deletedTxns.deletedCount} existing partner transactions for this shop/range`,
    );

    const txnDocs = [];
    for (const [name, txns] of Object.entries(partnerTxnsByName)) {
      txns.forEach((t) =>
        txnDocs.push({ ...t, partner: partnerMap[name], shop: SHOP_ID }),
      );
    }
    if (txnDocs.length) {
      const txnResult = await PartnerTransaction.insertMany(txnDocs, {
        ordered: true,
      });
      console.log(
        `Inserted ${txnResult.length} partner transactions for Metro Hospital, Haridwar`,
      );
    } else {
      console.log(
        "No partner transactions found in source data for Metro Hospital, Haridwar",
      );
    }

    const first = result[0];
    const last = result[result.length - 1];
    console.log(
      `Opening cash on ${first.date.toDateString()}: Rs ${first.openingCash}`,
    );
    console.log(
      `Closing cash on ${last.date.toDateString()}: Rs ${last.cashInHand}`,
    );
  } catch (err) {
    console.error("Seed failed:", err.message);
  } finally {
    await mongoose.connection.close();
    process.exit(0);
  }
};

run();
